"""add daily_metrics table

Revision ID: 39a82fe456d6
Revises: f5d4b73f5814
Create Date: 2026-08-13 04:24:34.805584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39a82fe456d6'
down_revision: Union[str, Sequence[str], None] = 'f5d4b73f5814'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_metrics',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('dimension', sa.String(length=128), nullable=False),
    sa.Column('value', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('date', 'metric', 'dimension', name=op.f('pk_daily_metrics'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_metrics')
    # ### end Alembic commands ###
