"""add has_exact_budget column to projects table

Revision ID: 40f3dd9ee629
Revises: 6905d70e51d3
Create Date: 2026-08-29 12:49:54.139744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40f3dd9ee629'
down_revision: Union[str, Sequence[str], None] = '6905d70e51d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('has_exact_budget', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'has_exact_budget')
    # ### end Alembic commands ###
