"""add updated_at column to projects table

Revision ID: 4954dd453ffa
Revises: f0940d043a91
Create Date: 2026-10-01 21:14:29.658594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4954dd453ffa'
down_revision: Union[str, Sequence[str], None] = 'f0940d043a91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.execute("UPDATE projects SET updated_at = created_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'updated_at')
    # ### end Alembic commands ###
