"""make_marketplace_customer_profile_fields_required

Revision ID: 5415a97d8ce1
Revises: 40f3dd9ee629
Create Date: 2026-09-07 10:40:29.706308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5415a97d8ce1'
down_revision: Union[str, Sequence[str], None] = '40f3dd9ee629'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('customers', 'user_projects_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('customers', 'user_hired_percent',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'user_hired_percent',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('customers', 'user_projects_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('customers', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
