"""add customers table

Revision ID: 6905d70e51d3
Revises: 4a947ecad16f
Create Date: 2026-08-20 06:38:00.959644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6905d70e51d3'
down_revision: Union[str, Sequence[str], None] = '4a947ecad16f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('profile_picture', sa.String(length=512), nullable=True),
    sa.Column('user_projects_count', sa.Integer(), nullable=True),
    sa.Column('user_hired_percent', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers')),
    sa.UniqueConstraint('external_id', 'source', name='uq_customer_external_id_source')
    )
    op.add_column('projects', sa.Column('customer_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_projects_customer_id_customers'), 'projects', 'customers', ['customer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_projects_customer_id_customers'), 'projects', type_='foreignkey')
    op.drop_column('projects', 'customer_id')
    op.drop_table('customers')
    # ### end Alembic commands ###
