"""add is_telegram_unavailable column to users table

Revision ID: 7d8fac159d65
Revises: 5415a97d8ce1
Create Date: 2026-09-30 15:53:07.477372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d8fac159d65'
down_revision: Union[str, Sequence[str], None] = '5415a97d8ce1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_telegram_unavailable', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_telegram_unavailable')
    # ### end Alembic commands ###
