"""add error column to project_notifications table

Revision ID: f0940d043a91
Revises: 7d8fac159d65
Create Date: 2026-09-30 20:13:53.126723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0940d043a91'
down_revision: Union[str, Sequence[str], None] = '7d8fac159d65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_notifications', sa.Column('error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "DELETE FROM project_notifications WHERE error IS NOT NULL",
    )
    op.drop_column('project_notifications', 'error')
    # ### end Alembic commands ###
