"""add article_images table and cover_image_id row to article table

Revision ID: f4f2cc7eb003
Revises: a3cdf541d9e4
Create Date: 2026-08-07 23:55:12.295080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4f2cc7eb003'
down_revision: Union[str, Sequence[str], None] = 'a3cdf541d9e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=True),
    sa.Column('filename', sa.String(length=128), nullable=False),
    sa.Column('content_type', sa.String(length=32), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_article_images_article_id_articles'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_article_images'))
    )
    op.create_index(op.f('ix_article_images_article_id'), 'article_images', ['article_id'], unique=False)
    op.add_column('articles', sa.Column('cover_image_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_articles_cover_image_id_article_images'), 'articles', 'article_images', ['cover_image_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_articles_cover_image_id_article_images'), 'articles', type_='foreignkey')
    op.drop_column('articles', 'cover_image_id')
    op.drop_index(op.f('ix_article_images_article_id'), table_name='article_images')
    op.drop_table('article_images')
    # ### end Alembic commands ###
