"""add source to project tables and make external_id string

Revision ID: f5d4b73f5814
Revises: f4f2cc7eb003
Create Date: 2026-08-10 04:41:04.019645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5d4b73f5814'
down_revision: Union[str, Sequence[str], None] = 'f4f2cc7eb003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_categories', sa.Column('source', sa.String(length=32), server_default='kwork', nullable=False))
    op.alter_column('project_categories', 'external_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=False,
               postgresql_using="external_id::character varying")
    op.create_unique_constraint('uq_project_categories_external_id_source', 'project_categories', ['external_id', 'source'])
    op.add_column('projects', sa.Column('source', sa.String(length=32), server_default='kwork', nullable=False))
    op.alter_column('projects', 'external_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=False,
               postgresql_using="external_id::character varying")
    op.drop_constraint(op.f('uq_projects_external_id'), 'projects', type_='unique')
    op.create_unique_constraint('uq_projects_external_id_source', 'projects', ['external_id', 'source'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_projects_external_id_source', 'projects', type_='unique')
    op.create_unique_constraint(op.f('uq_projects_external_id'), 'projects', ['external_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('projects', 'external_id',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=False,
               postgresql_using="external_id::integer")
    op.drop_column('projects', 'source')
    op.drop_constraint('uq_project_categories_external_id_source', 'project_categories', type_='unique')
    op.alter_column('project_categories', 'external_id',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=False,
               postgresql_using="external_id::integer")
    op.drop_column('project_categories', 'source')
    # ### end Alembic commands ###
